//! Standalone `vico-vee` service binary.
//!
//! Starts the ViCo Execution Environment as a separate HTTP server that ViCo
//! (or any other client) can reach over a well-defined REST API.

use clap::Parser;
use std::path::PathBuf;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};
use vico_vee::config::{Cli, Config, LogFormat};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    // CLI-only commands: run and exit.
    if let Some(maybe_path) = cli.generate_admin_key {
        let target = maybe_path.unwrap_or_else(|| {
            cli.config_dir
                .clone()
                .or_else(|| std::env::var("VICO_VEE_CONFIG_DIR").ok().map(PathBuf::from))
                .unwrap_or_else(vico_vee::paths::vee_config_dir)
                .join("api_keys.toml")
        });
        let token = generate_admin_key(&target)?;
        println!("generated admin API key: {token}");
        println!("wrote {target}", target = target.display());
        return Ok(());
    }

    let config = Config::load(Some(cli.clone()))?;

    // CLI-only commands: run and exit.
    if cli.backup {
        let path = vico_vee::backup::run_backup(&config, cli.backup_output)?;
        println!("backup created: {}", path.display());
        return Ok(());
    }
    if let Some(input) = cli.restore {
        vico_vee::backup::run_restore(&config, input)?;
        println!("restore completed");
        return Ok(());
    }

    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| "vico_vee=info,tower_http=info".into());

    match config.log_format {
        LogFormat::Json => {
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().json())
                .init();
        }
        LogFormat::Pretty => {
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer())
                .init();
        }
        LogFormat::Compact => {
            tracing_subscriber::registry()
                .with(env_filter)
                .with(tracing_subscriber::fmt::layer().compact())
                .init();
        }
    }

    let state = vico_vee::server::AppState::try_new(config.clone()).await?;

    let app = vico_vee::server::router(state);
    let listener = tokio::net::TcpListener::bind((config.bind.as_str(), config.port)).await?;

    let shutdown = async move {
        let _ = tokio::signal::ctrl_c().await;
    };

    if let (Some(cert_path), Some(key_path)) = (&config.tls_cert, &config.tls_key) {
        tracing::info!(
            bind = %config.bind,
            port = config.port,
            cert = %cert_path.display(),
            key = %key_path.display(),
            "vico-vee listening with TLS"
        );
        let tls_config = vico_vee::tls::TlsConfig::new(cert_path, key_path);
        let tls_reloader = vico_vee::tls::TlsReloader::new(&tls_config)?;
        tls_reloader.clone().spawn_sighup_reloader();
        vico_vee::tls::serve_https(listener, app, tls_reloader, shutdown).await?;
    } else {
        tracing::info!(bind = %config.bind, port = config.port, "vico-vee listening");
        axum::serve(listener, app)
            .with_graceful_shutdown(shutdown)
            .await?;
    }

    Ok(())
}

/// Generate a fresh admin API key and write it to `path` in the TOML format
/// expected by [`vico_vee::auth::AuthKeys`].
fn generate_admin_key(path: &PathBuf) -> Result<String, Box<dyn std::error::Error>> {
    use rand::RngCore;

    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    let token = hex::encode(bytes);

    let contents = format!(
        "# vico-vee API keys\n# Generated by --generate-admin-key\n[keys.admin]\ntoken = \"{token}\"\nscopes = [\"submit\", \"read\", \"admin\"]\n"
    );

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;

    Ok(token)
}
